describe('Para registration', () => {
    it('regitration form fill and assertion', () => {
        cy.visit('https://parabank.parasoft.com/')
        cy.get('#loginPanel > p:nth-child(3) > a').click()
        cy.get("input[id='customer.firstName']").type('Umair')
        cy.get("input[id='customer.lastName']").type('Anwar')
        cy.get("input[id='customer.address.street']").type('Abas block')
        cy.get("input[id='customer.address.city']").type('Lahore')
        cy.get("input[id='customer.address.state']").type('PAK')
        cy.get("input[id='customer.address.zipCode']").type('1234')
        cy.get("input[id='customer.phoneNumber']").type('12345678')
        cy.get("input[id='customer.ssn']").type('QWE')
        cy.get("input[id='customer.username']").type('test')
        cy.get("input[id='customer.password']").type('test123')
        cy.get("input[id='repeatedPassword']").type('test123')
        //cy.get('[colspan="2"] > .button').click()
        //cy.get('[type="submit"]').eq(1).click()
        cy.get('[type="submit"]').last().click()
        cy.get("span[id='customer.username.errors']").contains('This username already exists.')
        cy.get("input[name='username']").type('test')
        cy.get("input[name='password']").type('test123')
        cy.get('[type="submit"]').first().click()
        cy.get('#accountTable > tbody > tr:nth-child(1) > td:nth-child(1) > a').click()
        cy.get('#month').select('March')
        cy.get('#month').select('May')
        cy.get('#transactionType').select('Credit')
        cy.get('#activityForm > table > tbody > tr:nth-child(3) > td:nth-child(2) > input').click()

    })
})